#!/bin/bash
# /etc/NetworkManager/dispatcher.d/geoblog
 
IF=$1
STATUS=$2
 
cd /home/humitos/Source/blog/nikola

case "$2" in
    up)
    logger -s "NM Script 'geoblog' triggered"
    /home/humitos/.virtualenvs/blog/bin/python \
        geolocation.py --me

    # wait some time before copying the data
    sleep 15

    scp geodata/* \
        mkaufmann.com.ar:~/apps/blog.mkaufmann.com.ar/blog/nikola/output/assets/data/ &
    exit 0
    ;;
    *)
    ;;
esac

