#!/bin/bash
# /etc/NetworkManager/dispatcher.d/geoblog
 
IF=$1
STATUS=$2
 
cd /home/humitos/Source/blog/nikola
date >> geolocation.log

case "$2" in
    up)
    logger -s "NM Script 'geoblog' triggered"
    /home/humitos/.virtualenvs/blog/bin/python \
        geolocation.py >> geolocation.log &

    scp output/assets/js/point.json \
        mkaufmann.com.ar:~/apps/blog.mkaufmann.com.ar/blog/nikola/output/assets/js/point.json &
    exit 0
    ;;
    *)
    ;;
esac

